pipeline {
    agent any

    tools {
        python 'Python3'  // the name you configured in Global Tool Config
    }

    environment {
        PYTHON = "python3"
        PIP = "pip3" // pip3 install
        PROJECT_DIR = "messaging_app"
        REPORTS_DIR = "reports"
        TESTS_DIR = "tests"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Y-A-Dawit/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Prepare Project Structure') {
            steps {
                sh """
                    cd ${PROJECT_DIR}
                    mkdir -p ${REPORTS_DIR} ${TESTS_DIR}
                """
            }
        }

        stage('Install Dependencies') {
            steps {
                python requirements: 'messaging_app/requirements.txt', usePoetry: false
            }
        }

        stage('Run Tests') {
            steps {
                python command: 'messaging_app/pytest --maxfail=1 --disable-warnings -q \
                    --junitxml=messaging_app/reports/pytest-report.xml \
                    --html=messaging_app/reports/report.html --self-contained-html', 
                    usePoetry: false
            }
            post {
                always {
                    publishHTML([ 
                        reportDir: "messaging_app/reports",
                        reportFiles: "report.html",
                        reportName: "Pytest Report",
                        keepAll: true,
                        alwaysLinkToLastBuild: true,
                        allowMissing: true
                    ])
                }
            }
        }
    }

    post {
        success { echo 'Pipeline completed successfully ✅' }
        failure { echo 'Pipeline failed ❌ — check the Pytest Report' }
    }
}
