name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DATABASE_URL: mysql://test_user:test_pass@127.0.0.1:3306/test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt
          pip install pytest pytest-django pytest-html flake8 coverage

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h 127.0.0.1 -u test_user -ptest_pass && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run Flake8 Linting
        run: |
          flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 messaging_app --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Run Tests with Coverage
        run: |
          coverage run -m pytest messaging_app \
            --maxfail=1 --disable-warnings -q
          coverage xml -o messaging_app/reports/coverage.xml
          coverage html -d messaging_app/reports/coverage_html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: messaging_app/reports/report.html

      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            messaging_app/reports/coverage.xml
            messaging_app/reports/coverage_html
