pipeline {
    agent {
        docker {
            image 'python:3.11-slim'   // official Python image
            args '-u root:root'        // run as root inside container
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Y-A-Dawit/alx-backend-python.git', credentialsId: 'github-creds'
            }
        }

        stage('Install System Dependencies') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y gcc g++ make pkg-config libmariadb-dev libmariadb-dev-compat
                '''
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
